"""
EEG Pipeline Plotting Module

This module provides comprehensive plotting functionality for EEG/fMRI analysis organized
into domain-specific submodules: core utilities, ERP, features, TFR, behavioral, and decoding.

The module maintains backward compatibility where possible while providing a clean,
modular structure for future development.
"""

from .config import get_plot_config, PlotConfig

from .core import (
    get_font_sizes,
    log,
    format_cluster_significance_info,
    format_ttest_significance_info,
    build_significance_info,
    extract_valid_pvalues,
    apply_fdr_correction_to_roi_pvalues,
    find_annotation_x_position,
    build_roi_annotation_label,
    render_roi_annotations,
    add_normalized_colorbar,
    create_difference_colorbar,
    add_diff_colorbar,
    create_colorbar_for_topomaps,
    add_colorbar,
    build_topomap_diff_label,
    build_topomap_percentage_label,
    create_scalpmean_tfr_from_existing,
    get_strict_mode,
    compute_cluster_significance,
    compute_cluster_significance_from_combined,
    compute_significance_mask,
    build_statistical_title,
)

from .erp import (
    erp_contrast_pain,
    group_erp_contrast_pain,
    erp_by_temperature,
    group_erp_by_temperature,
    visualize_subject_erp,
    visualize_group_erp,
    visualize_erp_for_subjects,
)

from .features import (
    plot_power_distributions,
    plot_channel_power_heatmap,
    plot_power_time_courses,
    plot_power_spectral_density,
    plot_power_spectral_density_by_pain,
    plot_power_time_course_by_temperature,
    plot_trial_power_variability,
    plot_inter_band_spatial_power_correlation,
    plot_group_power_plots,
    plot_group_band_power_time_courses,
    plot_microstate_templates,
    plot_microstate_templates_by_pain,
    plot_microstate_templates_by_temperature,
    plot_microstate_coverage_by_pain,
    plot_microstate_pain_correlation_heatmap,
    plot_microstate_temporal_evolution,
    plot_microstate_gfp_colored_by_state,
    plot_microstate_gfp_by_temporal_bins,
    plot_microstate_transition_network,
    plot_microstate_duration_distributions,
    plot_group_microstate_template_stability,
    plot_group_microstate_transition_summary,
    plot_connectivity_circle_for_band,
    plot_sliding_connectivity_trajectories,
    plot_sliding_degree_heatmap,
    plot_edge_significance_circle_from_stats,
    plot_graph_metric_distributions,
    plot_graph_metrics_bar,
    plot_rsn_radar,
    plot_connectivity_heatmap,
    plot_connectivity_network,
    plot_sliding_state_centroids,
    plot_sliding_state_sequences,
    plot_sliding_state_occupancy_boxplot,
    plot_sliding_state_occupancy_ribbons,
    plot_sliding_state_lagged_correlation_surfaces,
    plot_itpc_heatmap,
    plot_itpc_topomaps,
    plot_itpc_behavior_scatter,
    plot_pac_comodulograms,
    plot_pac_time_ribbons,
    plot_pac_behavior_scatter,
    plot_aperiodic_r2_histogram,
    plot_aperiodic_residual_spectra,
    plot_aperiodic_run_trajectories,
    plot_aperiodic_topomaps,
    plot_aperiodic_vs_pain,
    visualize_subject_features,
    visualize_features_for_subjects,
)

from .tfr import (
    plot_cz_all_trials_raw,
    plot_cz_all_trials,
    plot_channels_all_trials,
    plot_scalpmean_all_trials,
    contrast_scalpmean_pain_nonpain,
    contrast_maxmin_temperature,
    plot_bands_pain_temp_contrasts,
    compute_roi_tfrs,
    plot_rois_all_trials,
    plot_topomap_grid_baseline_temps,
    plot_pain_nonpain_temporal_topomaps_diff_allbands,
    plot_temporal_topomaps_allbands_plateau,
    group_contrast_maxmin_temperature,
    group_rois_all_trials,
    group_contrast_pain_nonpain_rois,
    group_contrast_pain_nonpain_scalpmean,
    group_plot_bands_pain_temp_contrasts,
    group_plot_topomap_grid_baseline_temps,
    group_plot_pain_nonpain_temporal_topomaps_diff_allbands,
    group_plot_temporal_topomaps_allbands_plateau,
    group_tf_correlation,
    visualize_subject_tfr,
    visualize_group_tfr,
    visualize_tfr_for_subjects,
)

from .behavioral import (
    generate_correlation_scatter,
    plot_residual_qc,
    plot_regression_residual_diagnostics,
    plot_psychometrics,
    plot_power_roi_scatter,
    plot_group_power_roi_scatter,
    plot_temporal_correlation_topomaps_by_temperature,
    plot_temporal_correlation_topomaps_by_pain,
    plot_pain_nonpain_clusters,
    plot_regressor_distributions,
    plot_pac_behavior_correlations,
    plot_itpc_rating_scatter_grid,
    plot_group_temporal_topomaps,
    visualize_subject_behavior,
    visualize_group_behavior,
    visualize_behavior_for_subjects,
)

from .decoding import (
    plot_time_generalization_matrix,
    plot_time_generalization_with_null,
    plot_prediction_scatter,
    plot_per_subject_performance,
    plot_decoding_null_hist,
    plot_calibration_curve,
    plot_bootstrap_distributions,
    plot_permutation_null,
    plot_residual_diagnostics,
    plot_model_comparison,
    plot_riemann_band_comparison,
    plot_riemann_sliding_window,
    plot_incremental_validity,
    plot_feature_importance_top_n,
    plot_feature_importance_stability,
    visualize_regression_results,
    visualize_time_generalization,
    visualize_model_comparisons,
    visualize_riemann_analysis,
    visualize_incremental_validity,
)


__all__ = [
    # Configuration
    "get_plot_config",
    "PlotConfig",
    # Core utilities
    "get_font_sizes",
    "log",
    "format_cluster_significance_info",
    "format_ttest_significance_info",
    "build_significance_info",
    "extract_valid_pvalues",
    "apply_fdr_correction_to_roi_pvalues",
    "find_annotation_x_position",
    "build_roi_annotation_label",
    "render_roi_annotations",
    "add_normalized_colorbar",
    "create_difference_colorbar",
    "add_diff_colorbar",
    "create_colorbar_for_topomaps",
    "add_colorbar",
    "build_topomap_diff_label",
    "build_topomap_percentage_label",
    "create_scalpmean_tfr_from_existing",
    "get_strict_mode",
    "compute_cluster_significance",
    "compute_cluster_significance_from_combined",
    "compute_significance_mask",
    "build_statistical_title",
    # ERP plotting
    "erp_contrast_pain",
    "group_erp_contrast_pain",
    "erp_by_temperature",
    "group_erp_by_temperature",
    "visualize_subject_erp",
    "visualize_group_erp",
    "visualize_erp_for_subjects",
    # Features plotting
    "plot_power_distributions",
    "plot_channel_power_heatmap",
    "plot_power_time_courses",
    "plot_power_spectral_density",
    "plot_power_spectral_density_by_pain",
    "plot_power_time_course_by_temperature",
    "plot_trial_power_variability",
    "plot_inter_band_spatial_power_correlation",
    "plot_group_power_plots",
    "plot_group_band_power_time_courses",
    "plot_microstate_templates",
    "plot_microstate_templates_by_pain",
    "plot_microstate_templates_by_temperature",
    "plot_microstate_coverage_by_pain",
    "plot_microstate_pain_correlation_heatmap",
    "plot_microstate_temporal_evolution",
    "plot_microstate_gfp_colored_by_state",
    "plot_microstate_gfp_by_temporal_bins",
    "plot_microstate_transition_network",
    "plot_microstate_duration_distributions",
    "plot_group_microstate_template_stability",
    "plot_group_microstate_transition_summary",
    "plot_connectivity_circle_for_band",
    "plot_sliding_connectivity_trajectories",
    "plot_sliding_degree_heatmap",
    "plot_edge_significance_circle_from_stats",
    "plot_graph_metric_distributions",
    "plot_graph_metrics_bar",
    "plot_rsn_radar",
    "plot_connectivity_heatmap",
    "plot_connectivity_network",
    "plot_sliding_state_centroids",
    "plot_sliding_state_sequences",
    "plot_sliding_state_occupancy_boxplot",
    "plot_sliding_state_occupancy_ribbons",
    "plot_sliding_state_lagged_correlation_surfaces",
    "plot_itpc_heatmap",
    "plot_itpc_topomaps",
    "plot_itpc_behavior_scatter",
    "plot_pac_comodulograms",
    "plot_pac_time_ribbons",
    "plot_pac_behavior_scatter",
    "plot_aperiodic_r2_histogram",
    "plot_aperiodic_residual_spectra",
    "plot_aperiodic_run_trajectories",
    "plot_aperiodic_topomaps",
    "plot_aperiodic_vs_pain",
    "visualize_subject_features",
    "visualize_features_for_subjects",
    # TFR plotting
    "plot_cz_all_trials_raw",
    "plot_cz_all_trials",
    "plot_channels_all_trials",
    "plot_scalpmean_all_trials",
    "contrast_scalpmean_pain_nonpain",
    "contrast_maxmin_temperature",
    "plot_bands_pain_temp_contrasts",
    "compute_roi_tfrs",
    "plot_rois_all_trials",
    "plot_topomap_grid_baseline_temps",
    "plot_pain_nonpain_temporal_topomaps_diff_allbands",
    "plot_temporal_topomaps_allbands_plateau",
    "group_contrast_maxmin_temperature",
    "group_rois_all_trials",
    "group_contrast_pain_nonpain_rois",
    "group_contrast_pain_nonpain_scalpmean",
    "group_plot_bands_pain_temp_contrasts",
    "group_plot_topomap_grid_baseline_temps",
    "group_plot_pain_nonpain_temporal_topomaps_diff_allbands",
    "group_plot_temporal_topomaps_allbands_plateau",
    "group_tf_correlation",
    "visualize_subject_tfr",
    "visualize_group_tfr",
    "visualize_tfr_for_subjects",
    # Behavioral plotting
    "generate_correlation_scatter",
    "plot_residual_qc",
    "plot_regression_residual_diagnostics",
    "plot_psychometrics",
    "plot_power_roi_scatter",
    "plot_group_power_roi_scatter",
    "plot_temporal_correlation_topomaps_by_temperature",
    "plot_temporal_correlation_topomaps_by_pain",
    "plot_pain_nonpain_clusters",
    "plot_regressor_distributions",
    "plot_pac_behavior_correlations",
    "plot_itpc_rating_scatter_grid",
    "plot_group_temporal_topomaps",
    "visualize_subject_behavior",
    "visualize_group_behavior",
    "visualize_behavior_for_subjects",
    # Decoding plotting
    "plot_time_generalization_matrix",
    "plot_time_generalization_with_null",
    "plot_prediction_scatter",
    "plot_per_subject_performance",
    "plot_decoding_null_hist",
    "plot_calibration_curve",
    "plot_bootstrap_distributions",
    "plot_permutation_null",
    "plot_residual_diagnostics",
    "plot_model_comparison",
    "plot_riemann_band_comparison",
    "plot_riemann_sliding_window",
    "plot_incremental_validity",
    "plot_feature_importance_top_n",
    "plot_feature_importance_stability",
    "visualize_regression_results",
    "visualize_time_generalization",
    "visualize_model_comparisons",
    "visualize_riemann_analysis",
    "visualize_incremental_validity",
]

