#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/alliance_env.sh"

required_vars=(
    ALLIANCE_ACCOUNT
    REPO_ROOT
    EEG_PIPELINE_VENV
    BIDS_EEG_ROOT
    BIDS_FMRI_ROOT
    DERIV_ROOT
    STUDY2_SUBJECTS_DIR
    STUDY2_LOG_ROOT
    FS_LICENSE_FILE
    STUDY2_ENV_FILE
)
for variable_name in "${required_vars[@]}"; do
    if [[ -z "${!variable_name:-}" ]]; then
        echo "Required variable is empty: ${variable_name}" >&2
        exit 1
    fi
done

cat > "${STUDY2_ENV_FILE}" <<EOF
ALLIANCE_ACCOUNT=${ALLIANCE_ACCOUNT}
STUDY2_SLURM_MEMORY=${STUDY2_SLURM_MEMORY}
STUDY2_MODULES="StdEnv/2023 python/3.11 scipy-stack freesurfer"
STUDY2_REPO_ROOT=${REPO_ROOT}
STUDY2_VENV=${EEG_PIPELINE_VENV}
STUDY2_BIDS_EEG_ROOT=${BIDS_EEG_ROOT}
STUDY2_BIDS_MRI_ROOT=${BIDS_FMRI_ROOT}
STUDY2_DERIV_ROOT=${DERIV_ROOT}
STUDY2_SUBJECTS_DIR=${STUDY2_SUBJECTS_DIR}
STUDY2_LOG_ROOT=${STUDY2_LOG_ROOT}
STUDY2_FS_LICENSE=${FS_LICENSE_FILE}
STUDY2_SUBJECTS_FILE=${REPO_ROOT}/studies/pain_study/study2/alliance/subjects_study2.txt
STUDY2_CONFIG=${REPO_ROOT}/studies/pain_study/study2/config/study2_config.yaml
STUDY2_TASK=${STUDY2_TASK}
STUDY2_EEG_BIDS_RUN=
STUDY1_OUTPUT_ROOT_NAME=${STUDY1_OUTPUT_ROOT_NAME}
STUDY2_OUTPUT_ROOT_NAME=${STUDY2_OUTPUT_ROOT_NAME}
STUDY2_RECON_ARRAY_LIMIT=${STUDY2_RECON_ARRAY_LIMIT}
STUDY2_BEM_ARRAY_LIMIT=${STUDY2_BEM_ARRAY_LIMIT}
STUDY2_SOURCE_POWER_ARRAY_LIMIT=${STUDY2_SOURCE_POWER_ARRAY_LIMIT}
STUDY2_ADJACENCY_SUBJECT=${STUDY2_ADJACENCY_SUBJECT}
STUDY2_EXPECTED_VERTICES=${STUDY2_EXPECTED_VERTICES}
EOF

echo "Wrote ${STUDY2_ENV_FILE} for ${ALLIANCE_CLUSTER}."
